### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by DanTehrani** [personaelabs/nym#1]
_Developing the backend in [this](https://github.com/DanTehrani/nym-backend) repo._

## Todos
- [ ] Implement API endpoints
   - Implement the endpoints as defined [here](https://documenter.getpostman.com/view/19845036/2s93JzLLJ5). 
      - [Example](https://github.com/DanTehrani/nym-backend/blob/main/packages/nym-api/src/pages/api/v1/%5Bvenue%5D/merkle-trees/%5Broot%5D.ts)
- [ ] Merkle tree construction
   - [ ] Update tree on Noun contract updates
   - [ ] Update tree on multisig wallet updates
   - [ ] Handle public key unavailability

**Comment by cha0sg0d** [comment]
Still have public key unavailable and tree updating as not quite finalized.
